### ISSUE TITLE
Switching to other themes after material-ui is broken

### ISSUE THREAD

**Issue by WoodyWoodsta** [silvestreh/atom-material-ui#142]
Switching to any of the default themes (I've only tried the pre-installed ones) after using atom-material-ui leaves quite obvious traces of UI elements, fixable by restarting atom. Below is a screenshot:

![materialmess](https://cloud.githubusercontent.com/assets/8268040/11504051/1999ae46-984c-11e5-8537-c3bab093e6a7.png)

Atom V1.2.4, linux

**Comment by chazzlabs** [comment]
I'm seeing this as well and mentioned it in #141.

**Comment by WoodyWoodsta** [comment]
@chazzlabs Thought I would create a new issue, since it was about something different

**Comment by chazzlabs** [comment]
@WoodyWoodsta No problem; I just wanted to be sure the other issue was seen because I think they're related.  After reading the other issue and seeing the problem with default themes myself, it seemed that styles are being overridden across the board.

**Comment by silvestreh** [comment]
I… I have no idea what's happening. I'll have to investigate more because I'm not overriding anything. I'm not even sure you can override other theme's styles if the offending theme is deactivated.

**Comment by simurai** [comment]
It seems that when switching from `Atom Material 1.0` to `One dark`.. the switching of the theme works, but `Atom Material`s styles still stick around. And because they get loader later, they override the ones from `One dark`.

<img width="753" alt="screen shot 2015-12-04 at 3 36 38 pm" src="https://cloud.githubusercontent.com/assets/378023/11604161/c9403a4c-9a9d-11e5-8ae7-3ccdca13b876.png">

**Comment by silvestreh** [comment]
Thanks @simurai for spotting this one. It was driving me crazy :grin:

**Comment by simurai** [comment]
Did you get fixed? Awesome! :tada:

**Comment by WoodyWoodsta** [comment]
Thanks @simurai and @silvestreh - Always been my favourite theme!
