### ISSUE TITLE
Atom on laptop is stuck at version 0.8.0

### ISSUE THREAD

**Issue by skbolton** [silvestreh/atom-material-ui#156]
On my desktop I have the newest version of material-ui. On my laptop there is no way to get it to update past 0.8.0. I have made sure that my laptop atom version is up to date. Also I have uninstalled material-ui several times and reinstalled, each time it downloads version 0.8.0 and doesn't show me a way to update. Any idea on your end how I can force it to update?

Sorry for all the problems I have had lately :)
![atomproblem](https://cloud.githubusercontent.com/assets/13260877/11645553/a61a6548-9d12-11e5-81bb-c2b4d3bf830b.png)

**Comment by longhuei** [comment]
The developer has rolled back all versions beyond 0.8.0 since there have been multiple problems with the 1.0 release. The best way to go right now is to remove the newer version on your desktop and reinstall the material-ui package, which would come at version 0.8.0. If you insist on installing the latest testing release you can manually download the zip file and copy the folder to you ~/.atom/packages directory.

**Comment by silvestreh** [comment]
Yeah, like @longhuei suggested, if you want to use 1.0 grab the [repo zip](https://github.com/silvestreh/atom-material-ui/archive/master.zip) and extract it in `~/.atom/packages`.
