### ISSUE TITLE
Some text styles are white in the light version

### ISSUE THREAD

**Issue by jmanuel1** [silvestreh/atom-material-ui#158]
This makes some text very hard to read. For example: 
![image](https://cloud.githubusercontent.com/assets/7255867/11657590/c276dfe6-9df8-11e5-8683-5d74264ff68c.png)

According to the style guide, `@text-color-highlight` and  `@text-color-selected` are set to white. Maybe these are the culprits?

**Comment by silvestreh** [comment]
Thanks for the issue. Looks like you're using 0.8.0. Development focus in now on 1.0 which was published briefly some time ago and unpublished due to the number of bugs in it.

If you want to try the latest version, [download it](https://github.com/silvestreh/atom-material-ui/archive/master.zip) and unzip it to `C:\Users\jason\.atom\packages\`.

**Comment by jmanuel1** [comment]
Thanks! Awesome work!
