### ISSUE TITLE
Ui Slim Scrollbar Option doesn't seem to do anything

### ISSUE THREAD

**Issue by ramirezd42** [silvestreh/atom-material-ui#210]
Version 1.1.2: The Ui Slim Scrollbar Option doesn't seem to do anything when I toggle it and restart atom. Maybe I'm just not understanding what it's supposed to do. I was hoping maybe it would give me the old scrollbar back, I preferred that one personally.

**Comment by silvestreh** [comment]
You have a cache problem. The slim scrollbar option is no longer available as they're spec-compliant now.

Remove the `~/.atom/compile-cache/` directory and restart Atom. Also, open your `~/.atom/config.cson` file and remove all preferences in `atom-material-ui` so it looks like:

```cson
"atom-material-ui":
    colors: {}
    fonts: {}
    tabs: {}
    treeView: {}
    ui: {}
```

Or, instead of messing with the `config.cson` file, open the dev console and type `atom.config.set("atom-material-ui")` to reset your settings.

Oftentimes Atom fails to remove old settings and their controls will appear in a package's settings but won't have any effect.

If you absolutely want your thin scrollbars back, then open your personal stylesheet from `~/.atom/styles.less` and paste the following snippet:

```css
.scrollbars-visible-always /deep/::-webkit-scrollbar {
    width: 0.25rem;
    height: 0.25rem;
}
```

For reference, `1rem` is, by default, `16px` but you can change that in the theme's font-size setting. With default values, `0.25rem` should be equal to `4px`. Or define those dimensions in pixels if you like.

**Comment by ramirezd42** [comment]
Great. Thanks for the help!
