### ISSUE TITLE
Roboto Font doesn't appear to be working after 1.1.2 update

### ISSUE THREAD

**Issue by am17torres** [silvestreh/atom-material-ui#211]
I recently updated to atom-material-ui 1.1.2 and I noticed the Robot Font doesn't seem to be working anymore. 

Nothing changes when I check the boxes (which I believe it used to do on the fly). I've also tried restarting atom but that didn't make a difference. 

Here is a photo for reference. 

<img width="1892" alt="screen shot 2016-02-22 at 3 50 01 pm" src="https://cloud.githubusercontent.com/assets/70786/13232173/03cc55de-d97c-11e5-80cb-422967bad716.png">

Hopefully it's an easy fix because my UI looks pretty awful at the moment. Let me know if there is any more information that you need.

**Comment by silvestreh** [comment]
@am17torres Roboto Mono is no longer included. Those options were removed, but you're still seeing them because of a cache issue with Atom.

Open the dev console and run this: `atom.config.set("atom-material-ui");`. This will reset your theme's settings. Also, remove the ~/.atom/compile-cache/ directory and restart Atom.

If those options aren't going away, then open your ~/.atom/config.cson file and remove all preferences in `atom-material-ui` so it looks like:

```cson
"atom-material-ui":
    colors: {}
    fonts: {}
    tabs: {}
    treeView: {}
    ui: {}
```

If you want to use Roboto Mono, [Download it](https://www.google.com/fonts/specimen/Roboto+Mono), install it, and then change your Atom's (inside Editor Settings, **not** within the theme's settings) font family option.
