### ISSUE TITLE
Tabs disappear after they fill the viewport

### ISSUE THREAD

**Issue by leofle** [silvestreh/atom-material-ui#229]
When there is enough tabs to fill the viewport all the extra tabs disappear to the right, out of sight.
![screen shot 2016-02-25 at 8 54 36 am](https://cloud.githubusercontent.com/assets/2674606/13312233/973e437c-db9d-11e5-8751-e90b6b48243a.png)

**Comment by silvestreh** [comment]
Yeah, you should scroll your tab bar to get to the others.

**Comment by jamby** [comment]
Is there any way we can disable it? It's frustrating.

**Comment by christoga** [comment]
Don't open a lot of file then.

**Comment by WoodyWoodsta** [comment]
@jamby Could you offer an alternate solution then? If there were an option to disable it, what arrangement would be left as an alternative?

**Comment by jamby** [comment]
@christoga I don't usually like to, but since I can't see that I'm opening files since they don't fit, I don't realize it until too late.

@WoodyWoodsta Wouldn't a good way is let it be like the default Atom (or maybe it's just some other themes)? Basically, the more I open, the smaller and smaller the tabs get, even if I can't see the file names anymore.

The above way usually prompts me to close tabs because I can visually see I'm opening too many tabs, whereas the way now I don't even know I've opened that many tabs because it's out of the viewport.

**Comment by supremebeing7** [comment]
@jamby If you haven't already found a solution, you can edit the stylesheet to make this work the way you wish:

    .tab-bar {
      .tab {
        min-width: initial;
      }
    }

**Comment by supremebeing7** [comment]
(I also added `max-width: initial;` to make the tabs fill the entire tab bar - Example: http://i.imgur.com/rMHxYBt.png. Super helpful when I want to close a bunch of tabs at once when they start getting out of control.)

**Comment by jared-christensen** [comment]
I don't like part of the title getting cut off. Here is what I came up with.
https://gist.github.com/jared-christensen/29271832c56cb1c69ae6aef2312ae9d1

**Comment by gertsonderby** [comment]
Welp. The fact that this was just closed with no explanation by the maintainer, and ridiculed by community members (Seriously, "open fewer files", do you even code, bro?), means I'll be finding a different theme to use now. kthxbye.

**Comment by silvestreh** [comment]
@gertsonderby The [PR where this was resolved](https://github.com/atom-material/atom-material-ui/issues/298) is even mentioned in this issue.

![captura de pantalla 2016-09-21 a las 8 14 29 a m](https://cloud.githubusercontent.com/assets/1133339/18708873/73d3cc56-7fd3-11e6-85cb-79e6a3fbe2b2.png)

I can recommend SetiUI.

kthxbye.
