### ISSUE TITLE
blurry icons in tree view

### ISSUE THREAD

**Issue by treezrppl2** [silvestreh/atom-material-ui#235]
![screen shot 2016-03-02 at 10 29 36](https://cloud.githubusercontent.com/assets/10055135/13486838/58a1dada-e0c9-11e5-82f0-175164197536.png)
similar to #207 and #82 the tree-view icons are blurry again.
it looks like `.icon { webkit-font-smoothing: none; }` works as a hot fix, but I noticed that it's falling off the pixel grid because of sub-pixel sizing of the whole side-bar. It's likely the root of the problem lies with that `ol.tree-view.list-tree` .

**Comment by silvestreh** [comment]
Did you change the **User interface font size** setting within `atom-material-ui`? Because that would, obviously, change the size of everything in the viewport. The icons are designed to look best at certain size, even if they are vector icons. When you change that size they no longer align to a pixel grid. That's what makes them look blurry.

The only solution for this is to craft icons in every possible size, which would time consuming and is outside the scope of this theme.
