### ISSUE TITLE
Option for file-icons

### ISSUE THREAD

**Issue by Nxt3** [silvestreh/atom-material-ui#33]
I never found the icons on the tabs distracting. Would it be possible to get a setting for this?

**Comment by silvestreh** [comment]
I just pushed an update that adds an option to bring the icons back. This option is disabled by default because our implementation doesn't follow the Material Design Guidelines. If we make it follow the guidelines, it would look like utter crap. LOL.

I guess this is one of those few cases where Material Design doesn't fit properly.
