### ISSUE TITLE
Possible to make Icons optional?

### ISSUE THREAD

**Issue by tbremer** [silvestreh/atom-material-ui#63]
I know #61 introduced icons in, however some people use icon packages and that release doesn't allow those packages to work anymore. Possible to give an option?

**Comment by silvestreh** [comment]
Which icons package are you using? Right now [file-icons](https://atom.io/packages/file-icons) will display properly (in the treeview, I just noticed they're not showing in tabs)

**Comment by tbremer** [comment]
I am using a fork of file-icons called [envygeeks-file-icons](https://atom.io/packages/envygeeks-file-icons). I'll give file-icons a looksie.

**Comment by silvestreh** [comment]
I'm working on fixing this issue. I'll push an update ASAP!

**Comment by tbremer** [comment]
Looks like file-icons and envygeeks are using different specificity selectors. I'll can bring an issue to envy geeks github if you'd rather.

Thanks for the great UI! I switch syntax and UI themes all the time to try out new things, but this one always goes back into play pretty quickly. :beers:

**Comment by silvestreh** [comment]
@tbremer just pushed the update! Now I'm checking which packages are loaded programmatically rather than checking for classes in the DOM.

`file-icons`, `file-type-icons`, `seti-icons` and `envygeeks-file-icons` should all work now.

Thanks! Though most of the credit should go to @equinusocio for his Sublime theme. That's why I removed the donations link, it seemed unfair to him.

Cheers!

**Comment by diagramatics** [comment]
Instead of doing this programmatically is there no solution achievable with using :not() selectors?

**Comment by silvestreh** [comment]
@diagramatics Yeah, but only for `file-icons`. The rest: `file-type-icons`, `seti-icons` and `envygeeks-file-icons`; don't add classes to the DOM so I can't detect those.

**Comment by tbremer** [comment]
It's beautiful… thanks!

![icons](https://cloud.githubusercontent.com/assets/2998575/9254801/11209394-41ab-11e5-9509-f6fb553fb50e.png)

**Comment by diagramatics** [comment]
I wonder if we can knock the specificity down to a minimum somehow. I only checked file-type-icons and it seemed the package is using selectors very close to the default icons specificity. If we can override the default selectors with Material Icons and handle it from there maybe we can avoid programmatically checking the icon packages entirely.

`html:not(.dont-change-icons) .tree-view .list-group li .icon-file-text::before, html:not(.dont-change-icons) .tree-view .list-tree li .icon-file-text::before` is quite specific anyway. We can probably just override the `.icon-file-text::before` instead. I haven't checked the order of the CSS loaded into Atom, but hopefully themes are loaded first before packages.

**Comment by silvestreh** [comment]
Yep, guilty of over-nesting selectors. Though some of that probably came from Atom Dark UI as I started off of it.

**Comment by diagramatics** [comment]
I'll see if using low selectors will work on the file-icons packages you mentioned then. The compiled CSS will be quite a bloat considering that we have declarations of the Material Icons font being used and the size tweaks repeating on every single icon.

**Comment by silvestreh** [comment]
Yeah, that's probably the least elegant part of it. I wanted to start slowly with the icons, going one by one.  Not my brightest moment for sure. :smile:

**Comment by diagramatics** [comment]
Just checked this problem again, it seems we have no choice but to check packages programmatically. file-type-icons have the exact same selectors used by the base, and the theme seems to be loaded after the packages. We can't use selectors with lower dependency to make sure they're compatible because there are no gaps between the selectors.

I did knock the specificity though, but it should've ended up with more bloat.
